dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  npm: true
  directories:
    - node_modules
    - $(npm config get prefix)/bin/polymer-cli
    - $(npm config get prefix)/bin/wct-istanbul

language: node_js
node_js:
  - 10.16.0

branches:
  only:
  - master

before_install:
  - npm install polymer-cli -g
  - npm install web-component-tester-istanbulcoverage -g

install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  - npm test
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage