language: node_js
node_js:
  - 10.16.0
branches:
  only:
  - master
before_install:
  - npm install polymer-cli -g
  - npm install selenium-standalone@latest -g
install:
  - npm install
script:
  - npm test
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage